// Code generated by gerar.go from anexo_ii-sefin_adn-pedregevt_evt-snnfse-v1-01-20260122.xlsx; DO NOT EDIT.

package rejeicao

var anexoII = map[string][]Regra{
	"E0802": {
		{Mensagem: "Já existe um documento fiscal eletrônico identificado com este id no Sistema Nacional NFS-e.", Campo: "evento/infEvento/id", Texto: "O id do evento gerado já existe no ADN.", Nivel: ""},
	},
	"E0812": {
		{Mensagem: "O CNPJ do autor do pedido de registro de evento não corresponde à base do CNPJ informada no certificado digital da assinatura do pedido.", Campo: "evento/pedRegEvento/infPedReg/CNPJAutor", Texto: "Se o autor do pedido de registro de evento for identificado por um CNPJ este deve corresponder ao mesmo CNPJ do certificado digital da assinatura, se informada no pedido. \n\nVerificar apenas o CNPJ base.", Nivel: "1"},
	},
	"E0813": {
		{Mensagem: "O CNPJ autor informado no pedido de registro de evento não corresponde ao \"AUTOR DO PEDIDO DE REGISTRO DE EVENTO\" indicado na planilha \"Tipo Eventos\".", Campo: "evento/pedRegEvento/infPedReg/CNPJAutor", Texto: "O CNPJ autor identificado no pedido de registro de evento deve corresponder ao CNPJ conforme o \"AUTOR DO PEDIDO DE REGISTRO DE EVENTO\" da planilha \"Tipo Eventos\".", Nivel: "1"},
	},
	"E0815": {
		{Mensagem: "O CPF do autor do pedido de registro de evento não corresponde ao CPF informado no certificado digital da assinatura do pedido.", Campo: "evento/pedRegEvento/infPedReg/CPFAutor", Texto: "Se o autor do pedido de registro de evento for identificado por um CPF este deve corresponder ao mesmo CPF do certificado digital da assinatura, se informada no pedido.", Nivel: "1"},
	},
	"E0816": {
		{Mensagem: "O CPF autor informado no pedido de registro de evento não corresponde ao \"AUTOR DO PEDIDO DE REGISTRO DE EVENTO\" indicado na planilha \"Tipo Eventos\".", Campo: "evento/pedRegEvento/infPedReg/CPFAutor", Texto: "O CPF autor identificado no pedido de registro de evento deve corresponder ao CPF conforme o \"AUTOR DO PEDIDO DE REGISTRO DE EVENTO\" da planilha \"Tipo Eventos\".", Nivel: "1"},
	},
	"E0822": {
		{Mensagem: "O prazo para o cancelamento da NFS-e expirou, conforme parametrização do município emissor da NFS-e.", Campo: "evento/pedRegEvento/infPedReg/chNFSe", Texto: "Não pode ocorrer cancelamento de NFS-e fora do prazo limite para o cancelamento da NFS-e, conforme parametrização do município emissor da NFS-e.", Nivel: "3"},
	},
	"E0823": {
		{Mensagem: "Valor da NFS-e a ser cancelada acima do permitido, conforme parametrização do município emissor da NFS-e.", Campo: "evento/pedRegEvento/infPedReg/chNFSe", Texto: "Não pode ocorrer cancelamento de NFS-e acima de valor permitido pelo município emissor da NFS-e, conforme parametrização do município emissor da NFS-e.", Nivel: "3"},
	},
	"E0824": {
		{Mensagem: "NFS-e sem indentificação do tomador do serviço não pode ser cancelada, conforme parametrização do município emissor da NFS-e.", Campo: "evento/pedRegEvento/infPedReg/chNFSe", Texto: "Não pode ocorrer o cancelamento de NFS-e que não esteja identificado o tomador de serviço, conforme parametrização do município emissor da NFS-e.", Nivel: "3"},
	},
	"E0827": {
		{Mensagem: "Não é permitido realizar um Evento de Cancelamento para NFS-e que possua Evento de Tributos Recolhidos vinculado, conforme parametrização do município de incidência do ISSQN da NFS-e.", Campo: "evento/pedRegEvento/infPedReg/chNFSe", Texto: "Não é permitido realizar um Evento de Cancelamento para NFS-e que possua Evento de Tributos Recolhidos vinculado, conforme parametrização do município de incidência do ISSQN da NFS-e.", Nivel: "3"},
	},
	"E0831": {
		{Mensagem: "O pedido de registro deste evento de NFS-e deve ser enviado para o ambiente que gerou a NFS-e referenciada no pedido.", Campo: "evento/pedRegEvento/infPedReg/chNFSe", Texto: "O pedido de registro deste evento de NFS-e deve ser enviado para o ambiente que gerou a NFS-e referenciada no pedido.", Nivel: "1"},
	},
	"E0840": {
		{Mensagem: "O Sistema Nacional NFS-e não pode recepecionar o EVENTO DE CANCELAMENTO DE NFS-e pois, o evento de <nome_evento_vinculado_a_NFS-e> já está vinculado à NFS-e indicada no evento enviado, impedindo sua recepção.", Campo: "evento/pedRegEvento/infPedReg/e101101", Texto: "O Sistema Nacional NFS-e deve responder à recepção do EVENTO DE CANCELAMENTO NFS-e, conforme indicado nas linhas da respectiva coluna deste evento na planilha \"RN EVENTOSxEVENTOS - Sistema Nacional NFS-e\".", Nivel: "1"},
	},
	"E0845": {
		{Mensagem: "O Sistema Nacional NFS-e não pode recepecionar o EVENTO DE CANCELAMENTO DE NFS-e POR SUBSTITUIÇÃO pois, o evento de <nome_evento_vinculado_a_NFS-e> já está vinculado à NFS-e indicada no evento enviado, impedindo sua recepção.", Campo: "evento/pedRegEvento/infPedReg/e105102", Texto: "O Sistema Nacional NFS-e deve responder à recepção do EVENTO DE CANCELAMENTO DE NFS-e POR SUBSTITUIÇÃO, conforme indicado nas linhas da respectiva coluna deste evento na planilha \"RN EVENTOSxEVENTOS - Sistema Nacional NFS-e\".", Nivel: "1"},
	},
	"E0848": {
		{Mensagem: "O Sistema Nacional NFS-e não pode recepecionar o EVENTO DE SOLICITAÇÃO DE ANÁLISE FISCAL PARA CANCELAMENTO DE NFS-e pois, o evento de <nome_evento_vinculado_a_NFS-e> já está vinculado à NFS-e indicada no evento enviado, impedindo sua recepção.", Campo: "evento/pedRegEvento/infPedReg/e101103", Texto: "O Sistema Nacional NFS-e deve responder à recepção do EVENTO DE SOLICITAÇÃO DE ANÁLISE FISCAL PARA CANCELAMENTO DE NFS-e, conforme indicado nas linhas da respectiva coluna deste evento na planilha \"RN EVENTOSxEVENTOS - Sistema Nacional NFS-e\".", Nivel: "1"},
	},
	"E0852": {
		{Mensagem: "O Sistema Nacional NFS-e não pode recepecionar o EVENTO DE CANCELAMENTO DE NFS-e DEFERIDO POR ANÁLISE FISCAL pois, o evento de <nome_evento_vinculado_a_NFS-e> já está vinculado à NFS-e indicada no evento enviado, impedindo sua recepção.", Campo: "evento/pedRegEvento/infPedReg/e105104", Texto: "O Sistema Nacional NFS-e deve responder à recepção do EVENTO DE CANCELAMENTO DE NFS-e DEFERIDO POR ANÁLISE FISCAL, conforme indicado nas linhas da respectiva coluna deste evento na planilha \"RN EVENTOSxEVENTOS - Sistema Nacional NFS-e\".", Nivel: "1"},
	},
	"E0853": {
		{Mensagem: "O Sistema Nacional NFS-e não pode recepecionar o EVENTO DE CANCELAMENTO DE NFS-e DEFERIDO POR ANÁLISE FISCAL pois não existe um EVENTO DE SOLICITAÇÃO DE ANÁLISE FISCAL PARA CANCELAMENTO DE NFS-e pendente para deferimento ou indeferimento.", Campo: "evento/pedRegEvento/infPedReg/e105104", Texto: "Não é permitida a recepção do deferimento de uma solicitação de cancelamento por análise fiscal sem que haja um Evento de Solicitação de Análise Fiscal para Cancelamento de NFS-e, que esteja pendente de deferimento ou indeferimento.", Nivel: "1"},
	},
	"E0855": {
		{Mensagem: "O Sistema Nacional NFS-e não pode recepecionar o EVENTO DE CANCELAMENTO DE NFS-E INDEFERIDO POR ANÁLISE FISCAL pois, o evento de <nome_evento_vinculado_a_NFS-e> já está vinculado à NFS-e indicada no evento enviado, impedindo sua recepção.", Campo: "evento/pedRegEvento/infPedReg/e105105", Texto: "O Sistema Nacional NFS-e deve responder à recepção do EVENTO DE CANCELAMENTO DE NFS-E INDEFERIDO POR ANÁLISE FISCAL, conforme indicado nas linhas da respectiva coluna deste evento na planilha \"RN EVENTOSxEVENTOS - Sistema Nacional NFS-e\".", Nivel: "1"},
	},
	"E0856": {
		{Mensagem: "O Sistema Nacional NFS-e não pode recepecionar o EVENTO DE CANCELAMENTO DE NFS-e INDEFERIDO POR ANÁLISE FISCAL pois não existe um EVENTO DE SOLICITAÇÃO DE ANÁLISE FISCAL PARA CANCELAMENTO DE NFS-e pendente para deferimento ou indeferimento.", Campo: "evento/pedRegEvento/infPedReg/e105105", Texto: "Não é permitida a recepção do indeferimento de uma solicitação de cancelamento por análise fiscal sem que haja um Evento de Solicitação de Análise Fiscal para Cancelamento de NFS-e, que esteja pendente de deferimento ou indeferimento.", Nivel: "1"},
	},
	"E0860": {
		{Mensagem: "O Sistema Nacional NFS-e não pode recepecionar o EVENTO DE MANIFESTAÇÃO DE NFS-e - CONFIRMAÇÃO DO PRESTADOR pois, o evento de <nome_evento_vinculado_a_NFS-e> já está vinculado à NFS-e indicada no evento enviado, impedindo sua recepção.", Campo: "evento/pedRegEvento/infPedReg/e202201", Texto: "O Sistema Nacional NFS-e deve responder à recepção do EVENTO DE MANIFESTAÇÃO DE NFS-e - CONFIRMAÇÃO DO PRESTADOR, conforme indicado nas linhas da respectiva coluna deste evento na planilha \"RN EVENTOSxEVENTOS - Sistema Nacional NFS-e\".", Nivel: "1"},
	},
	"E0861": {
		{Mensagem: "O Sistema Nacional NFS-e não pode recepecionar o EVENTO DE MANIFESTAÇÃO DE NFS-e - CONFIRMAÇÃO DO TOMADOR pois, o evento de <nome_evento_vinculado_a_NFS-e> já está vinculado à NFS-e indicada no evento enviado, impedindo sua recepção.", Campo: "evento/pedRegEvento/infPedReg/e203202", Texto: "O Sistema Nacional NFS-e deve responder à recepção do EVENTO DE MANIFESTAÇÃO DE NFS-e - CONFIRMAÇÃO DO TOMADOR, conforme indicado nas linhas da respectiva coluna deste evento na planilha \"RN EVENTOSxEVENTOS - Sistema Nacional NFS-e\".", Nivel: "1"},
	},
	"E0862": {
		{Mensagem: "O Sistema Nacional NFS-e não pode recepecionar o EVENTO DE MANIFESTAÇÃO DE NFS-e - CONFIRMAÇÃO DO INTERMEDIÁRIO pois, o evento de <nome_evento_vinculado_a_NFS-e> já está vinculado à NFS-e indicada no evento enviado, impedindo sua recepção.", Campo: "evento/pedRegEvento/infPedReg/e204203", Texto: "O Sistema Nacional NFS-e deve responder à recepção do EVENTO DE MANIFESTAÇÃO DE NFS-e - CONFIRMAÇÃO DO INTERMEDIÁRIO, conforme indicado nas linhas da respectiva coluna deste evento na planilha \"RN EVENTOSxEVENTOS - Sistema Nacional NFS-e\".", Nivel: "1"},
	},
	"E0863": {
		{Mensagem: "O Sistema Nacional NFS-e não pode recepecionar o EVENTO DE MANIFESTAÇÃO DE NFS-e - CONFIRMAÇÃO TÁCITA pois, o evento de <nome_evento_vinculado_a_NFS-e> já está vinculado à NFS-e indicada no evento enviado, impedindo sua recepção.", Campo: "evento/pedRegEvento/infPedReg/e205204", Texto: "O Sistema Nacional NFS-e deve responder à recepção do EVENTO DE MANIFESTAÇÃO DE NFS-e - CONFIRMAÇÃO TÁCITA, conforme indicado nas linhas da respectiva coluna deste evento na planilha \"RN EVENTOSxEVENTOS - Sistema Nacional NFS-e\".", Nivel: "1"},
	},
	"E0864": {
		{Mensagem: "O Sistema Nacional NFS-e não pode recepecionar o EVENTO DE MANIFESTAÇÃO DE NFS-e - REJEIÇÃO DO PRESTADOR pois, o evento de <nome_evento_vinculado_a_NFS-e> já está vinculado à NFS-e indicada no evento enviado, impedindo sua recepção.", Campo: "evento/pedRegEvento/infPedReg/e202205", Texto: "O Sistema Nacional NFS-e deve responder à recepção do EVENTO DE MANIFESTAÇÃO DE NFS-e - REJEIÇÃO DO PRESTADOR, conforme indicado nas linhas da respectiva coluna deste evento na planilha \"RN EVENTOSxEVENTOS - Sistema Nacional NFS-e\".", Nivel: "1"},
	},
	"E0866": {
		{Mensagem: "O Sistema Nacional NFS-e não pode recepecionar o EVENTO DE MANIFESTAÇÃO DE NFS-e - REJEIÇÃO DO TOMADOR pois, o evento de <nome_evento_vinculado_a_NFS-e> já está vinculado à NFS-e indicada no evento enviado, impedindo sua recepção.", Campo: "evento/pedRegEvento/infPedReg/e203206", Texto: "O Sistema Nacional NFS-e deve responder à recepção do EVENTO DE MANIFESTAÇÃO DE NFS-e - REJEIÇÃO DO TOMADOR, conforme indicado nas linhas da respectiva coluna deste evento na planilha \"RN EVENTOSxEVENTOS - Sistema Nacional NFS-e\".", Nivel: "1"},
	},
	"E0868": {
		{Mensagem: "O Sistema Nacional NFS-e não pode recepecionar o EVENTO DE MANIFESTAÇÃO DE NFS-e - REJEIÇÃO DO INTERMEDIÁRIO pois, o evento de <nome_evento_vinculado_a_NFS-e> já está vinculado à NFS-e indicada no evento enviado, impedindo sua recepção.", Campo: "evento/pedRegEvento/infPedReg/e204207", Texto: "O Sistema Nacional NFS-e deve responder à recepção do EVENTO DE MANIFESTAÇÃO DE NFS-e - REJEIÇÃO DO INTERMEDIÁRIO, conforme indicado nas linhas da respectiva coluna deste evento na planilha \"RN EVENTOSxEVENTOS - Sistema Nacional NFS-e\".", Nivel: "1"},
	},
	"E0870": {
		{Mensagem: "O Sistema Nacional NFS-e não pode recepecionar o EVENTO DE MANIFESTAÇÃO DE NFS-e - ANULAÇÃO DA REJEIÇÃO pois, o evento de <nome_evento_vinculado_a_NFS-e> já está vinculado à NFS-e indicada no evento enviado, impedindo sua recepção.", Campo: "evento/pedRegEvento/infPedReg/e205208", Texto: "O Sistema Nacional NFS-e deve responder à recepção do EVENTO DE MANIFESTAÇÃO DE NFS-e - ANULAÇÃO DA REJEIÇÃO, conforme indicado nas linhas da respectiva coluna deste evento na planilha \"RN EVENTOSxEVENTOS - Sistema Nacional NFS-e\".", Nivel: "1"},
	},
	"E1260": {
		{Mensagem: "O prazo de aceitação da versão do leiaute do DF-e expirou.", Campo: "evento/versao", Texto: "O prazo de aceitação da versão do leiaute do DF-e ultrapassado.", Nivel: "1"},
	},
	"E1278": {
		{Mensagem: "A data e hora do processamento (geração) do DF-e deve ser anterior ou igual à data da recepção pelo Sistema Nacional NFS-e.", Campo: "evento/infEvento/dhProc", Texto: "A data/hora do registro do evento deve ser anterior à data/hora do processamento do documento pelo Sistema Nacional NFS-e.", Nivel: "1"},
	},
	"E1802": {
		{Mensagem: "Conteúdo do identificador informado no identificador do evento difere da concatenação dos campos correspondentes.", Campo: "evento/infEvento/id", Texto: "Campo identificador do Evento (EVT) inválido.\n\nIdentificador do evento difere da concatenação dos campos correspondentes existente no leiaute evento.\n\nA formação deste identificador considera o literal \"EVT\" associado a outras 59 posições numéricas, \nconforme descrito abaixo:\n\n\"EVT\" + \nid do Pedido de Registo de Evento (56) + \nNúmero sequencial do evento (nSeqEvento) (3)", Nivel: "1"},
	},
	"E1825": {
		{Mensagem: "Prazo de aceitação da versão do leiaute do pedido de registro de evento expirou.", Campo: "evento/pedRegEvento/versao", Texto: "Prazo de aceitação da versão do leiaute do pedido de registro de evento ultrapassado.", Nivel: "1"},
	},
	"E1827": {
		{Mensagem: "Conteúdo do identificador informado no identificador do Pedido de Registro de Evento difere da concatenação dos campos correspondentes.", Campo: "evento/pedRegEvento/infPedReg/id", Texto: "Campo identificador do Pedido de Registro de Evento (PRE) inválido.\n\nIdentificador do PRE difere da concatenação dos campos correspondentes existente no leiaute do PRE.\n\nA formação deste identificador considera o literal \"PRE\" associado a outras 56 posições numéricas, conforme descrito abaixo:\n\n\"PRE\" + \nChave de acesso da NFS-e (50) +\nCódigo do evento (6)", Nivel: "1"},
	},
	"E1831": {
		{Mensagem: "O pedido de registro de evento não pode ser validado pois a NFS-e indicada não existe no Ambiente de Dados Nacional NFS-e.", Campo: "evento/pedRegEvento/infPedReg/chNFSe", Texto: "A NFS-e indicada não existe no ADN NFS-e.", Nivel: "1"},
	},
	"E1833": {
		{Mensagem: "Somente é permitido um único evento do tipo Manifestação de NFS-e (Confirmação e Rejeição), por não emitente da NFS-e indicada no evento.", Campo: "evento/pedRegEvento/infPedReg/chNFSe", Texto: "Somente é permitido um único evento do tipo Manifestação de NFS-e (Confirmação e Rejeição), se o autor do evento, informado nos campos CNPJAutor ou CPFAutor, corresponder aos possíveis não emitentes da NFS-e indicada pela chave de acesso.", Nivel: "1"},
	},
	"E1835": {
		{Mensagem: "Somente é permitido um único evento do tipo Manifestação de NFS-e (Anulação da Rejeição) para cada Evento de Manifestação de NFS-e - Rejeição, emitido por cada possível não emitentes da NFS-e indicada pela chave de acesso.", Campo: "evento/pedRegEvento/infPedReg/chNFSe", Texto: "Somente é permitido um único evento do tipo Manifestação de NFS-e (Anulação da Rejeição) para cada Evento de Manifestação de NFS-e - Rejeição, emitido por cada um dos possíveis não emitentes da NFS-e indicada pela chave de acesso.", Nivel: "1"},
	},
	"E1845": {
		{Mensagem: "Ambiente informado diverge do ambiente de recebimento para o qual o emitente está enviando o evento.", Campo: "evento/pedRegEvento/infPedReg/tpAmb", Texto: "Tipo do ambiente informado difere do ambiente utilizado.", Nivel: "1"},
	},
	"E1944": {
		{Mensagem: "A  descrição do motivo é obrigatória caso o tipo do motivo seja \"9 - Outros\".", Campo: "evento/pedRegEvento/infPedReg/e202205/xMotivo", Texto: "Se o campo cMotivo for igual a \"9, - Outros\", então a descrição do motivo tem preenchimento obrigatório.", Nivel: "1"},
	},
	"E1949": {
		{Mensagem: "A  descrição do motivo é obrigatória caso o tipo do motivo seja \"9 - Outros\".", Campo: "evento/pedRegEvento/infPedReg/e203206/xMotivo", Texto: "Se o campo cMotivo for igual a \"9, - Outros\", então a descrição do motivo tem preenchimento obrigatório.", Nivel: "1"},
	},
	"E1954": {
		{Mensagem: "A  descrição do motivo é obrigatória caso o tipo do motivo seja \"9 - Outros\".", Campo: "evento/pedRegEvento/infPedReg/e204207/xMotivo", Texto: "Se o campo cMotivo for igual a \"9, - Outros\", então a descrição do motivo tem preenchimento obrigatório.", Nivel: ""},
	},
	"E1960": {
		{Mensagem: "O Sistema Nacional NFS-e não pode recepecionar o EVENTO DE CANCELAMENTO DE NFS-e POR OFÍCIO pois, o evento de <nome_evento_vinculado_a_NFS-e> já está vinculado à NFS-e indicada no evento enviado, impedindo sua recepção.", Campo: "evento/pedRegEvento/infPedReg/e305101", Texto: "O Sistema Nacional NFS-e deve responder à recepção do EVENTO DE CANCELAMENTO DE NFS-e POR OFÍCIO, conforme indicado nas linhas da respectiva coluna deste evento na planilha \"RN EVENTOSxEVENTOS - Sistema Nacional NFS-e\".", Nivel: "1"},
	},
	"E1963": {
		{Mensagem: "O identificador do Evento de Manifestação de NFS-e - Rejeição a ser anulado deve existir no Sistema Nacional NFS-e e corresponder a um identificador de evento de rejeição vinculada à NFS-e informada no evento.", Campo: "evento/pedRegEvento/infPedReg/e205208/idEvManifRej", Texto: "O identificador do Evento de Manifestação de NFS-e - Rejeição a ser anulado deve existir no Sistema Nacional NFS-e e corresponder a um identificador de evento de rejeição vinculada à NFS-e informada no evento.", Nivel: "1"},
	},
	"E1965": {
		{Mensagem: "O Sistema Nacional NFS-e não pode recepecionar o EVENTO DE BLOQUEIO DE NFS-e POR OFÍCIO pois, o evento de <nome_evento_vinculado_a_NFS-e> já está vinculado à NFS-e indicada no evento enviado, impedindo sua recepção.", Campo: "evento/pedRegEvento/infPedReg/e305102", Texto: "O Sistema Nacional NFS-e deve responder à recepção do EVENTO DE BLOQUEIO DE NFS-e POR OFÍCIO, conforme indicado nas linhas da respectiva coluna deste evento na planilha \"RN EVENTOSxEVENTOS - Sistema Nacional NFS-e\".", Nivel: "1"},
	},
	"E1967": {
		{Mensagem: "O sistema não pode recepcionar o Evento de Bloqueio de NFS-e por Ofício para <tipo_evento_bloqueio_NFS-e>, pois já existe o mesmo tipo de evento vinculado à NFS-e sem o Evento de Desbloqueio correpondente.", Campo: "evento/pedRegEvento/infPedReg/e305102/codEvento", Texto: "O Evento de Bloqueio de NFS-e para um tipo de evento, deve ser rejeitado se já houver um evento de bloqueio de NFS-e para o mesmo tipo do evento que não esteja desbloquedo.\n\nObs: Verificar se para cada evento de bloqueio de NFS-e para um tipo de evento existe o correspondente desbloqueio.\n\nSe os possíveis eventos de bloqueios de NFS-e para um tipo de evento não estiverem todos pareados com os seus respectivos desbloqueios, então o eveto de bloqueio de NFS-e do mesmo tipo que está sendo recepcionado pelo Sistema Nacional NFS-e deverá ser rejeitado.", Nivel: "1"},
	},
	"E1970": {
		{Mensagem: "O Sistema Nacional NFS-e não pode recepecionar o EVENTO DE DESBLOQUEIO DE NFS-e POR OFÍCIO pois, o evento de <nome_evento_vinculado_a_NFS-e> já está vinculado à NFS-e indicada no evento enviado, impedindo sua recepção.", Campo: "evento/pedRegEvento/infPedReg/e305103", Texto: "O Sistema Nacional NFS-e deve responder à recepção do EVENTO DE DESBLOQUEIO DE NFS-e POR OFÍCIO, conforme indicado nas linhas da respectiva coluna deste evento na planilha \"RN EVENTOSxEVENTOS - Sistema Nacional NFS-e\".", Nivel: "1"},
	},
	"E1976": {
		{Mensagem: "Não existe o identificador de bloqueio informado neste evento para desbloqueio.", Campo: "evento/pedRegEvento/infPedReg/e305103/idBloqOfic", Texto: "O evento de Evento de Desbloqueio de NFS-e deve ser rejeitado se o identificador do bloqueio de oficio, indicado neste evento, não existir.", Nivel: "1"},
	},
	"E1978": {
		{Mensagem: "O sistema não pode recepcionar o Evento Desbloqueio de NFS-e por Ofício, pois o Evento de Bloqueio indicado já foi desbloqueado.", Campo: "evento/pedRegEvento/infPedReg/e305103/idBloqOfic", Texto: "O Evento de Desbloqueio de NFS-e deve ser rejeitado se o identificador do bloqueio de oficio, indicado neste evento, já tiver sido desbloqueado.", Nivel: "1"},
	},
	"E1980": {
		{Mensagem: "Arquivo enviado com erro na assinatura.", Campo: "evento/pedRegEvento/Signature", Texto: "A assinatura do Pedido de Registro de Evento deve ser válida.", Nivel: "1"},
	},
	"E1983": {
		{Mensagem: "Certificado Digital da assinatura inválido.", Campo: "evento/pedRegEvento/Signature", Texto: "Certificado Digital da assintura inválido:\n\n- Validade do Certificado (data início e data fim);\n- Verifica a Cadeia de Certificação;\n- Certificado do Transmissor revogado;\n- LCR indisponível ou inválida.", Nivel: "1"},
	},
	"E1986": {
		{Mensagem: "Certificado Digital fora do padrão estabelecido.", Campo: "evento/pedRegEvento/Signature", Texto: "Certificado Digital da assinatura fora do padrão estabelecido pelo projeto NFS-e:\n\n- Versão diferente de 3;\n- Se informado, Basic Constraint deve ser true (não pode ser Certificado de AC);\n- KeyUsage não define 'Assinatura Digital' e 'Não Recusa';\n- Falta a extensão de CNPJ (OtherName - OID=2.16.76.1.3.3) ou CPF (OtherName - OID=2.16.76.1.3.1);\n- Certificado Raiz difere da 'ICP-Brasil'.", Nivel: "1"},
	},
	"E1989": {
		{Mensagem: "A assinatura é obrigatória quando for enviado para o Web Service.", Campo: "evento/pedRegEvento/Signature", Texto: "É obrigatória a existência da assinatura do Pedido de Registro de Evento quando for enviado para Web Service.", Nivel: "1"},
	},
	"E1991": {
		{Mensagem: "A assinatura deve ser feita com o certificado digital do emitente do Pedido de Registro de Evento.", Campo: "evento/pedRegEvento/Signature", Texto: "A assinatura deve ser feita com o certificado digital do emitente do Pedido de Registro de Evento.", Nivel: "1"},
	},
}
