//go:build ignore

// Command gerar rebuilds anexo_i.go from the government spreadsheet.
//
//	go run gerar.go [-saida arquivo.go]
//
// The source of truth is ANEXO I, versioned in docs/anexos/ and read by
// internal/anexoi, the same reader the documentation site uses. The table is
// committed because it goes into the binary, which carries no spreadsheet and
// no reader for one (ADR 0019).
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path"

	"github.com/edusouza/nfse-emissor-go/internal/anexoi"
)

func main() {
	saida := flag.String("saida", "anexo_i.go", "arquivo Go a gerar")
	flag.Parse()

	rejeicoes, err := anexoi.Ler(anexoi.Caminho())
	if err != nil {
		log.Fatal(err)
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by gerar.go from %s; DO NOT EDIT.\n\n", path.Base(anexoi.Arquivo))
	b.WriteString("package rejeicao\n\n")
	b.WriteString("var anexoI = map[string][]Regra{\n")
	for _, r := range rejeicoes {
		fmt.Fprintf(&b, "%q: {\n", r.Codigo)
		for _, regra := range r.Regras {
			fmt.Fprintf(&b, "{Mensagem: %q, Campo: %q, Texto: %q, Nivel: %q},\n",
				regra.Mensagem, regra.Campo, regra.Texto, regra.Nivel)
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n")

	codigo, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatalf("o codigo gerado nao compila: %v", err)
	}
	if err := os.WriteFile(*saida, codigo, 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%s: %d codigos\n", *saida, len(rejeicoes))
}
