//go:build ignore

// Command gerar rebuilds anexo_i.go and anexo_ii.go from the government
// spreadsheets.
//
//	go run gerar.go [-dir diretorio]
//
// The source of truth is the annexes, versioned in docs/anexos/ and read by
// internal/anexos, the same reader the documentation site uses. The tables are
// committed because they go into the binary, which carries no spreadsheet and
// no reader for one (ADR 0019).
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path"
	"path/filepath"

	"github.com/edusouza/nfse-emissor-go/internal/anexos"
)

func main() {
	dir := flag.String("dir", ".", "diretorio onde gravar os arquivos gerados")
	flag.Parse()

	tabelas := []struct {
		arquivo  string
		ler      func(string) ([]anexos.Rejeicao, error)
		saida    string
		variavel string
	}{
		{anexos.ArquivoI, anexos.LerI, "anexo_i.go", "anexoI"},
		{anexos.ArquivoII, anexos.LerII, "anexo_ii.go", "anexoII"},
	}
	for _, t := range tabelas {
		rejeicoes, err := t.ler(anexos.Caminho(t.arquivo))
		if err != nil {
			log.Fatal(err)
		}
		saida := filepath.Join(*dir, t.saida)
		if err := gravar(saida, t.variavel, path.Base(t.arquivo), rejeicoes); err != nil {
			log.Fatal(err)
		}
		fmt.Printf("%s: %d codigos\n", saida, len(rejeicoes))
	}
}

func gravar(saida, variavel, origem string, rejeicoes []anexos.Rejeicao) error {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by gerar.go from %s; DO NOT EDIT.\n\n", origem)
	b.WriteString("package rejeicao\n\n")
	fmt.Fprintf(&b, "var %s = map[string][]Regra{\n", variavel)
	for _, r := range rejeicoes {
		fmt.Fprintf(&b, "%q: {\n", r.Codigo)
		for _, regra := range r.Regras {
			fmt.Fprintf(&b, "{Mensagem: %q, Campo: %q, Texto: %q, Nivel: %q},\n",
				regra.Mensagem, regra.Campo, regra.Texto, regra.Nivel)
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n")

	codigo, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("o codigo gerado nao compila: %w", err)
	}
	return os.WriteFile(saida, codigo, 0o644)
}
